#!/bin/bash
#----------------------------------------------------
# SLURM job script to run MPI applications on 
# TACC's Stampede system.
#
#----------------------------------------------------

#SBATCH -J myMPIjob           # Job name
#SBATCH -o myjob.%j.out       # Name of stdout output file (%j expands to jobId)
#SBATCH -p development        # Queue name
#SBATCH -N 2                  # Total number of nodes requested (16 cores/node)
#SBATCH -n 32                 # Total number of mpi tasks requested
#SBATCH -t 01:30:00           # Run time (hh:mm:ss) - 1.5 hours

#SBATCH -A TG-ASC170005      # <-- Allocation name to charge job against

# Launch the MPI executable named "a.out"

ibrun ./test3  


